In [1]:
import numpy as np

In [38]:
arr = np.array([10, 20, 30, 40, 50])
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [39]:
arr_2d[1, 2]

np.int64(7)

In [40]:
arr_2d[1: , 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
arr = np.random.randint(1, 50, size=15)

In [74]:
arr[arr > 25]

array([30, 26, 27, 28, 47, 29])

In [75]:
arr_1 = np.random.randint(1, 100000, 100)

In [76]:
arr_1[(arr_1 % 2 == 0) & (arr_1 < 10000)]

array([8222, 2180, 5268, 5500])

In [77]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
arr[[2, 0, 4, 6]]

array([30, 10, 50, 70])

In [82]:
arr[[2, 4, 6]] = [1, 3, 8]

In [83]:
arr

array([10, 20,  1, 40,  3, 60,  8, 80, 90])

In [127]:
list_1 = [1, 2, 3, 4, 5]
arr_1 = np.array([1, 2, 3, 4, 5])

In [ ]:
temp_list = list_1[1:4] # copy
temp_arr = arr_1[1:4] # view

In [134]:
temp_list

[2, 3, 4]

In [135]:
temp_arr

array([2, 3, 4])

In [136]:
temp_list[1] = 0
temp_arr[1] = 0

In [138]:
temp_list

[2, 0, 4]

In [139]:
temp_arr

array([2, 0, 4])

In [140]:
list_1

[1, 2, 3, 4, 5]

In [141]:
arr_1

array([1, 2, 0, 4, 5])

# Practice Exercises: Analyzing Temperature Data

You are given a NumPy array `temperatures` that contains the daily temperature readings for a city over a period of one week. The array has shape `(7, 24)`, representing 7 days and 24 hourly temperature readings per day.


In [174]:
import numpy as np

temperatures = np.array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
                         [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
                         [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                          25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
                         [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                          26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
                         [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                          27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
                         [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17],
                         [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                          29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18]])

Your task is to perform the following operations using indexing and slicing:

1. Extract the temperature readings for the first day.
2. Extract the temperature readings for the last day.
3. Extract the temperature readings for the first 12 hours of each day.
4. Extract the temperature readings for the last 6 hours of each day.
5. Extract the temperature readings for every other hour of the fourth day.
6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher.
7. Create a boolean mask to find all temperature readings above 25 degrees.


In [175]:
first_day_temps = temperatures[0]
first_day_temps

array([12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 23, 22, 21, 20, 19,
       18, 17, 16, 15, 14, 13, 12])

In [176]:
last_day_temps = temperatures[-1]
last_day_temps

array([18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20, 19, 18])

In [177]:
first_12hr_temps = temperatures[: , 0:13]
first_12hr_temps

array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 23],
       [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 24],
       [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 25],
       [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 26],
       [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 27],
       [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 28],
       [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 29]])

In [178]:
last_6hr_temps = temperatures[: , -6:]
last_6hr_temps

array([[17, 16, 15, 14, 13, 12],
       [18, 17, 16, 15, 14, 13],
       [19, 18, 17, 16, 15, 14],
       [20, 19, 18, 17, 16, 15],
       [21, 20, 19, 18, 17, 16],
       [22, 21, 20, 19, 18, 17],
       [23, 22, 21, 20, 19, 18]])

In [179]:
fourth_day_temps = temperatures[3, ::2]
fourth_day_temps

array([15, 18, 20, 22, 24, 26, 26, 24, 22, 20, 18, 16])

In [180]:
temperatures[4, :3] += 10

In [184]:
above_25_mask = temperatures > 25 # The boolean mask
above_25_temps = temperatures[above_25_mask]
above_25_temps

array([26, 26, 27, 26, 26, 28, 29, 26, 27, 28, 27, 26, 26, 27, 28, 29, 28,
       27, 26, 26, 27, 28, 29, 30, 29, 28, 27, 26])