In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [16]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = arr.ravel()
new_arr[0] *= 10
arr

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

In [27]:
arr  = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = arr.flatten()
new_arr[0] *= 10
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
arr_1 = np.array([[1, 2], [3, 4], [5, 6]])
new_arr_1 = arr_1.ravel()
new_arr_1[0] *= 10

arr_2 = np.array([[1, 2], [3, 4], [5, 6]])
new_arr_2 = arr_2.flatten()
new_arr_2[0] *= 10

print(f'{arr_1}\n\n{arr_2}')

[[10  2]
 [ 3  4]
 [ 5  6]]

[[1 2]
 [3 4]
 [5 6]]


## Practice Exercise: Analyzing Sales Data

You are given two NumPy arrays `sales_2021` and `sales_2022` that contain the monthly sales data for a company over the past two years. Each array has shape `(3, 4)`, representing sales data for 3 products over 4 quarters.

In [35]:
sales_2021 = np.array([[100, 120, 140, 160],
                       [200, 220, 240, 260],
                       [300, 320, 340, 360]])

sales_2022 = np.array([[110, 130, 150, 170],
                       [210, 230, 250, 270],
                       [310, 330, 350, 370]])

Your task is to perform the following operations:

1. Combine the sales data for both years into a single array using vertical stacking.
2. Reshape the combined sales data into a 1D array.
3. Split the combined sales data into separate arrays for each product using horizontal splitting.
4. Create a new array that repeats the sales data for each year twice using tiling.
5. Calculate the total sales for each year using flattening and summation.

In [40]:
combined_sales = np.vstack((sales_2021, sales_2022))
combined_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

In [42]:
flattened_sales = np.ravel(combined_sales)
flattened_sales

array([100, 120, 140, 160, 200, 220, 240, 260, 300, 320, 340, 360, 110,
       130, 150, 170, 210, 230, 250, 270, 310, 330, 350, 370])

In [55]:
seperated_arrs = np.vsplit(combined_sales, 3)
print('Sales Data for Each Product:\n')
for i, product in enumerate(seperated_arrs, start=1):
    print(f'Product number {i}:\n{product}\n\n')

Sales Data for Each Product:

Product number 1:
[[100 120 140 160]
 [200 220 240 260]]


Product number 2:
[[300 320 340 360]
 [110 130 150 170]]


Product number 3:
[[210 230 250 270]
 [310 330 350 370]]




In [60]:
tiled_sales = np.tile(combined_sales, (2, 1))
tiled_sales

array([[100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370],
       [100, 120, 140, 160],
       [200, 220, 240, 260],
       [300, 320, 340, 360],
       [110, 130, 150, 170],
       [210, 230, 250, 270],
       [310, 330, 350, 370]])

In [65]:
total_sales_2021 = np.sum(np.ravel(sales_2021))
total_sales_2022 = np.sum(np.ravel(sales_2022))

print('Total Sales for Each Year:\n')
print(f'Year 2021: {total_sales_2021}\nYear 2022: {total_sales_2022}')

Total Sales for Each Year:

Year 2021: 2760
Year 2022: 2880
