In [1]:
import numpy as np

In [10]:
random_numbers = np.random.randint(1, 10000, (5, 3))

In [17]:
np.where(random_numbers > 5000)

(array([1, 2, 3, 3, 3, 4, 4, 4]), array([1, 0, 0, 1, 2, 0, 1, 2]))

In [13]:
random_numbers

array([[4015, 4640, 3063],
       [ 478, 5124, 2450],
       [9301, 1640, 2303],
       [9300, 5475, 5104],
       [6329, 8275, 5937]])

In [22]:
arr = np.random.randint(1, 1000, (10, 10))

In [23]:
filtered_arr = np.where(arr > 500, 0, arr)
filtered_arr

array([[138, 463, 342,   0,   0,   0,   0, 313,   0, 340],
       [  0,   0,   0,   0,   0,   0,  47, 283,   0, 159],
       [165, 473,   0,   0, 450,   0, 431, 213,   0, 352],
       [438,   0,   0,   0, 218,   0, 462,   0, 204,  67],
       [  0,   0,   0,   0,   0, 131,   0, 438,   0,   0],
       [  0,   0, 255, 147, 316,   0,   0,   0,   0, 346],
       [161, 117,  62,   0, 498, 225,  51, 117, 484,   0],
       [  0,   0,   0, 460, 472,   0, 161, 293,   0,   0],
       [  0, 346,  83, 210, 487,   0,   0, 464,   0, 243],
       [  0, 394,  11, 445,  74,  24, 170,   0,  93,   0]])

In [25]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_arr = np.unique(arr)
unique_arr, counts = np.unique(arr, return_counts=True)
print(f'{unique_arr}\n{counts}')

[1 2 3 4 5]
[1 2 1 2 1]


# Practice Exercise: Analyzing Student Grades

You are given a NumPy array `grades` that contains the grades of a group of students in a course. Your task is to perform the following operations:

1. Sort the grades in ascending order.
2. Find the top 5 grades using array slicing.
3. Determine the number of students who passed the course (grade >= 60).
4. Identify the students who scored below the mean grade.
5. Find the unique grades in the array.

In [32]:
grades = np.array([85, 72, 90, 68, 77, 82, 92, 60, 55, 75, 88, 80, 95, 78, 65])

In [33]:
sorted_grades = np.sort(grades)
sorted_grades

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])

In [38]:
top_5_grades = sorted_grades[-1:-6:-1]
top_5_grades

array([95, 92, 90, 88, 85])

In [40]:
passed_students = np.where(grades >= 60)
print(np.size(passed_students))

14


In [43]:
mean_grade = np.mean(grades)
grades_below_mean = np.where(grades < mean_grade)
grades[grades_below_mean]

array([72, 68, 77, 60, 55, 75, 65])

In [44]:
unique_grades = np.unique(grades)
unique_grades

array([55, 60, 65, 68, 72, 75, 77, 78, 80, 82, 85, 88, 90, 92, 95])