In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4])

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.zeros((2, 3))
# 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [50]:
arr_1 = np.random.rand(2)
arr_2= np.random.randint(3, 10, size=3)

In [51]:
arr_2

array([6, 3, 9])

# Practice Exercise: Analyzing Customer Data

You are working with customer data for an e-commerce company. The data includes customer IDs, ages, and purchase amounts. Your task is to create NumPy arrays to store and analyze this data.

1. Create a 1-dimensional NumPy array called `customer_ids` that contains the following customer IDs: 1001, 1002, 1003, 1004, 1005.

2. Create a 1-dimensional NumPy array called `ages` that contains the ages of the customers: 25, 30, 35, 40, 45. Use the `np.arange()` function to create this array.

3. Create a 2-dimensional NumPy array called `purchase_amounts` that contains the purchase amounts for each customer over three months:
   - Month 1: 100, 200, 300, 400, 500
   - Month 2: 150, 250, 350, 450, 550
   - Month 3: 200, 300, 400, 500, 600

4. Create a 3-dimensional NumPy array called `sales_data` that combines the customer IDs, ages, and purchase amounts. The shape of the array should be (5, 3, 2), where:
   - The first dimension represents the customers
   - The second dimension represents the months
   - The third dimension represents the customer ID and age for each customer

5. Create a NumPy array called `large_purchases` that contains the purchase amounts greater than 300. Use boolean indexing to create this array.

6. Create a random integer array called `random_purchases` with shape (3, 5) that represents random purchase amounts between 100 and 1000.

In [ ]:
customer_ids = np.array([1001, 1002, 1003, 1004, 1005])
ages = np.arange(25, 50, 5)
purchase_amounts = [
    [100, 200, 300, 400, 500],
    [150, 250, 350, 450, 550],
    [200, 300, 400, 500, 600]
]
