In [1]:
import numpy as np

In [2]:
np.linspace(1, 20, 4)
# Generates 4 numbers between 1 and 20

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [6]:
np.zeros((3, 4))
# np.zeros and np.ones get a TUPLE.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.diag([1, 3, 10])
# The `np.diag()` function is used to create a 2-dimensional diagonal matrix. A diagonal matrix is a matrix with non-zero elements only on the main diagonal. 
# It takes a 1-dimensional array or a list as input, representing the diagonal elements.

array([[ 1,  0,  0],
       [ 0,  3,  0],
       [ 0,  0, 10]])

In [15]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

# Common NumPy Data Types:

NumPy provides a wide range of data types to suit different numerical requirements. Here are some commonly used NumPy data types:

- **Integer Types**:
  - `np.int8`: 8-bit signed integer
  - `np.int16`: 16-bit signed integer
  - `np.int32`: 32-bit signed integer (default integer type)
  - `np.int64`: 64-bit signed integer
  - `np.uint8`: 8-bit unsigned integer
  - `np.uint16`: 16-bit unsigned integer
  - `np.uint32`: 32-bit unsigned integer
  - `np.uint64`: 64-bit unsigned integer

- **Floating-Point Types**:
  - `np.float16`: 16-bit half-precision floating-point
  - `np.float32`: 32-bit single-precision floating-point
  - `np.float64`: 64-bit double-precision floating-point (default float type)

- **Complex Types**:
  - `np.complex64`: Complex number represented by two 32-bit floats
  - `np.complex128`: Complex number represented by two 64-bit floats

- **Boolean Type**:
  - `np.bool`: Boolean (True or False)

- **String Type**:
  - `np.str`: String (fixed-length)

- **Object Type**:
  - `np.object`: Python object

## np.random:

In [ ]:
np.random.rand(2, 3)
# Generates an array with random numbers.
# Args: axis

array([[0.35009109, 0.78049909, 0.28689354],
       [0.46123707, 0.12931998, 0.96513266]])

In [35]:
arr_1 = np.random.randint(3, 10, 3)
arr_2 = np.random.randint(3, 10, size=(4, 3))
# Frist and second args: range
# Third arg: axis

In [36]:
arr_1

array([5, 3, 4])

In [37]:
arr_2

array([[3, 6, 9],
       [4, 5, 4],
       [4, 5, 8],
       [6, 9, 4]])