In [2]:
import numpy as np

In [2]:
np.linspace(1, 20, 4)
# Generates 4 numbers between 1 and 20

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [6]:
np.zeros((3, 4))
# np.zeros and np.ones get a TUPLE.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.diag([1, 3, 10])
# The `np.diag()` function is used to create a 2-dimensional diagonal matrix. A diagonal matrix is a matrix with non-zero elements only on the main diagonal. 
# It takes a 1-dimensional array or a list as input, representing the diagonal elements.

array([[ 1,  0,  0],
       [ 0,  3,  0],
       [ 0,  0, 10]])

In [15]:
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

# Common NumPy Data Types:

NumPy provides a wide range of data types to suit different numerical requirements. Here are some commonly used NumPy data types:

- **Integer Types**:
  - `np.int8`: 8-bit signed integer
  - `np.int16`: 16-bit signed integer
  - `np.int32`: 32-bit signed integer (default integer type)
  - `np.int64`: 64-bit signed integer
  - `np.uint8`: 8-bit unsigned integer
  - `np.uint16`: 16-bit unsigned integer
  - `np.uint32`: 32-bit unsigned integer
  - `np.uint64`: 64-bit unsigned integer

- **Floating-Point Types**:
  - `np.float16`: 16-bit half-precision floating-point
  - `np.float32`: 32-bit single-precision floating-point
  - `np.float64`: 64-bit double-precision floating-point (default float type)

- **Complex Types**:
  - `np.complex64`: Complex number represented by two 32-bit floats
  - `np.complex128`: Complex number represented by two 64-bit floats

- **Boolean Type**:
  - `np.bool`: Boolean (True or False)

- **String Type**:
  - `np.str`: String (fixed-length)

- **Object Type**:
  - `np.object`: Python object

## np.random:

In [ ]:
np.random.rand(2, 3)
# Generates an array with random numbers.
# Args: axis

array([[0.35009109, 0.78049909, 0.28689354],
       [0.46123707, 0.12931998, 0.96513266]])

In [35]:
arr_1 = np.random.randint(3, 10, 3)
arr_2 = np.random.randint(3, 10, size=(4, 3))
# Frist and second args: range
# Third arg: axis

In [36]:
arr_1

array([5, 3, 4])

In [37]:
arr_2

array([[3, 6, 9],
       [4, 5, 4],
       [4, 5, 8],
       [6, 9, 4]])

In [5]:
# Boolean Indexing
# arr[Boolean Condition -> a condition that return a boolean array]
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, False, False, True])
result = arr[mask]
result

array([1, 5])

In [6]:
arr_1 = np.random.randint(1, 100000, 100)
arr_1[(arr_1 % 2 == 0) & (arr_1 < 10000)]

array([9428, 2478, 2882])

In [9]:
# Fancy Indexing
# arr[[Indices]]
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
arr[[2, 0, 4, 6]]

array([30, 10, 50, 70])

In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = arr_2d[row_indices, col_indices]
result

array([2, 6, 7])

In [16]:
# View vs. Copy
list_1 = [1, 2, 3, 4, 5]
arr_1 = np.array([1, 2, 3, 4, 5])

temp_list = list_1[1:4] # copy
temp_arr = arr_1[1:4] # view

temp_list[1] = 0 # Modifies the copy version of the list.
temp_arr[1] = 0 # Modifies the main array because the slicing and temp_arr is just a view.

print(list_1, arr_1)

# Note: If you really need to avoid modifying the original array, use the .copy() method before making any changes.

[1, 2, 3, 4, 5] [1 2 0 4 5]


In [20]:
print(np.shares_memory(temp_list, list_1), np.shares_memory(temp_arr, arr_1))

False True
